CREATE TABLE games (
    player_id integer,
    game_id long,
    date datetime,
    opp varchar(10),
    win integer,
    team_score integer,
    opp_score integer,
    start integer,
    min float,
    fgm integer,
    fga integer,
    tpm integer,
    tpa integer,
    ftm integer,
    fta integer,
    def integer,
    off integer,
    reb integer,
    ast integer,
    turnovers integer,
    stl integer,
    blk integer,
    pf integer,
    pts integer);

